filter:
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: false
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        newline_at_end_of_file: true
        encourage_single_quotes: true
tools:
    external_code_coverage: false
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR4
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        filter:
            paths: ['src']
    php_cpd:
        enabled: true
